markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Error On Line One
production_url : http://erroronlineone.com
description: ""
# disqus_shortname: caarlos0blog
# analytics: UA-32899481-1
# gauges: 50f2b533613f5d7c8000000c
author :
  name : William Horbelt
  github : WilliamHorbelt
  email: williamhorbelt@gmail.com
